CREATE OR REPLACE WAREHOUSE GOLD_WH
WITH 
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;
CREATE OR REPLACE DATABASE GOLD_PROJECT;
CREATE OR REPLACE SCHEMA GOLD_PROJECT.RAW_DATA;
CREATE OR REPLACE SCHEMA GOLD_PROJECT.PROCESSED;
